/*
	This project is released under the GPL 2.0 license.
	Please do no evil.

	Initial author: (https://github.com/)Convery
	Started: 2015-04-08
	Notes:
		Just to make it a little easier to handle the interfaces.
*/

#pragma once

#define ADD_INTERFACE(interfaceId, type) case interfaceId: return new type; break; 

enum SteamInterface_t
{
	INTERFACE_STEAMAPPS001,
	INTERFACE_STEAMAPPS002,
	INTERFACE_STEAMAPPS003,
	INTERFACE_STEAMAPPS004,
	INTERFACE_STEAMAPPS005,
	INTERFACE_STEAMAPPS006,
	INTERFACE_STEAMAPPS007,

	INTERFACE_STEAMBILLING001,
	INTERFACE_STEAMBILLING002,
	INTERFACE_STEAMBILLING003,

	INTERFACE_STEAMCLIENT001,
	INTERFACE_STEAMCLIENT002,
	INTERFACE_STEAMCLIENT003,
	INTERFACE_STEAMCLIENT004,
	INTERFACE_STEAMCLIENT005,
	INTERFACE_STEAMCLIENT006,
	INTERFACE_STEAMCLIENT007,
	INTERFACE_STEAMCLIENT008,
	INTERFACE_STEAMCLIENT009,
	INTERFACE_STEAMCLIENT010,
	INTERFACE_STEAMCLIENT011,
	INTERFACE_STEAMCLIENT012,
	// [...]
	INTERFACE_STEAMCLIENT016,
	INTERFACE_STEAMCLIENT017,

	INTERFACE_STEAMCONTENTSERVER001,
	INTERFACE_STEAMCONTENTSERVER002,

	INTERFACE_STEAMFRIENDS001,
	INTERFACE_STEAMFRIENDS002,
	INTERFACE_STEAMFRIENDS003,
	INTERFACE_STEAMFRIENDS004,
	INTERFACE_STEAMFRIENDS005,
	INTERFACE_STEAMFRIENDS006,
	INTERFACE_STEAMFRIENDS007,
	INTERFACE_STEAMFRIENDS008,
	INTERFACE_STEAMFRIENDS009,
	INTERFACE_STEAMFRIENDS010,
	INTERFACE_STEAMFRIENDS011,
	INTERFACE_STEAMFRIENDS012,
	INTERFACE_STEAMFRIENDS013,
	INTERFACE_STEAMFRIENDS014,
	INTERFACE_STEAMFRIENDS015,

	INTERFACE_STEAMGAMECOORDINATOR001,

	INTERFACE_STEAMGAMESERVER001,
	INTERFACE_STEAMGAMESERVER002,
	INTERFACE_STEAMGAMESERVER003,
	INTERFACE_STEAMGAMESERVER004,
	INTERFACE_STEAMGAMESERVER005,
	INTERFACE_STEAMGAMESERVER006,
	INTERFACE_STEAMGAMESERVER007,
	INTERFACE_STEAMGAMESERVER008,
	INTERFACE_STEAMGAMESERVER009,
	INTERFACE_STEAMGAMESERVER010,
	INTERFACE_STEAMGAMESERVER011,
	INTERFACE_STEAMGAMESERVER012,

	INTERFACE_STEAMGAMESERVERSTATS001,

	INTERFACE_STEAMGAMESTATS001,

	INTERFACE_STEAMHTTP001,
	INTERFACE_STEAMHTTP002,

	INTERFACE_STEAMMASTERUPDATER001,

	INTERFACE_STEAMMATCHMAKING001,
	INTERFACE_STEAMMATCHMAKING002,
	INTERFACE_STEAMMATCHMAKING003,
	INTERFACE_STEAMMATCHMAKING004,
	INTERFACE_STEAMMATCHMAKING005,
	INTERFACE_STEAMMATCHMAKING006,
	INTERFACE_STEAMMATCHMAKING007,
	INTERFACE_STEAMMATCHMAKING008,
	INTERFACE_STEAMMATCHMAKING009,

	INTERFACE_STEAMMATCHMAKINGSERVERS001,
	INTERFACE_STEAMMATCHMAKINGSERVERS002,

	INTERFACE_STEAMMUSIC001,

	INTERFACE_STEAMNETWORKING001,
	INTERFACE_STEAMNETWORKING002,
	INTERFACE_STEAMNETWORKING003,
	INTERFACE_STEAMNETWORKING004,
	INTERFACE_STEAMNETWORKING005,

	INTERFACE_STEAMOAUTH001,

	INTERFACE_STEAMREMOTESTORAGE001,
	INTERFACE_STEAMREMOTESTORAGE002,
	INTERFACE_STEAMREMOTESTORAGE003,
	INTERFACE_STEAMREMOTESTORAGE004,
	INTERFACE_STEAMREMOTESTORAGE005,
	INTERFACE_STEAMREMOTESTORAGE006,
	INTERFACE_STEAMREMOTESTORAGE007,
	INTERFACE_STEAMREMOTESTORAGE008,
	INTERFACE_STEAMREMOTESTORAGE009,
	INTERFACE_STEAMREMOTESTORAGE010,
	INTERFACE_STEAMREMOTESTORAGE011,
	INTERFACE_STEAMREMOTESTORAGE012,

	INTERFACE_STEAMSCREENSHOTS001,
	INTERFACE_STEAMSCREENSHOTS002,

	INTERFACE_STEAMSTREAMLAUNCHER001,

	INTERFACE_STEAMUGC001,
	INTERFACE_STEAMUGC002,

	INTERFACE_STEAMUNIFIEDMESSAGES001,

	INTERFACE_STEAMUSER001,
	INTERFACE_STEAMUSER002,
	INTERFACE_STEAMUSER003,
	INTERFACE_STEAMUSER004,
	INTERFACE_STEAMUSER005,
	INTERFACE_STEAMUSER006,
	INTERFACE_STEAMUSER007,
	INTERFACE_STEAMUSER008,
	INTERFACE_STEAMUSER009,
	INTERFACE_STEAMUSER010,
	INTERFACE_STEAMUSER011,
	INTERFACE_STEAMUSER012,
	INTERFACE_STEAMUSER013,
	INTERFACE_STEAMUSER014,
	INTERFACE_STEAMUSER015,
	INTERFACE_STEAMUSER016,
	INTERFACE_STEAMUSER017,

	INTERFACE_STEAMUSERSTATS001,
	INTERFACE_STEAMUSERSTATS002,
	INTERFACE_STEAMUSERSTATS003,
	INTERFACE_STEAMUSERSTATS004,
	INTERFACE_STEAMUSERSTATS005,
	INTERFACE_STEAMUSERSTATS006,
	INTERFACE_STEAMUSERSTATS007,
	INTERFACE_STEAMUSERSTATS008,
	INTERFACE_STEAMUSERSTATS009,
	INTERFACE_STEAMUSERSTATS010,
	INTERFACE_STEAMUSERSTATS011,

	INTERFACE_STEAMUTILS001,
	INTERFACE_STEAMUTILS002,
	INTERFACE_STEAMUTILS003,
	INTERFACE_STEAMUTILS004,
	INTERFACE_STEAMUTILS005,
	INTERFACE_STEAMUTILS006,
	INTERFACE_STEAMUTILS007,
};

class InterfaceManager
{
	static std::unordered_map<SteamInterface_t, void *> Instances;
	static void *CreateInterface(SteamInterface_t interfaceID);

	static const char* SteamInterfaces[];

public:
	static void *GetInterface(SteamInterface_t interfaceID);
};