/*
	This project is released under the GPL 2.0 license.
	Please do no evil.

	Initial author: (https://github.com/)Convery
	Started: 2015-04-08
	Notes:
		Just to make it a little easier to handle the interfaces.
*/

#include "..\STDInc.h"

const char* InterfaceManager::SteamInterfaces[] =
{
	"INTERFACE_STEAMAPPS001",
	"INTERFACE_STEAMAPPS002",
	"INTERFACE_STEAMAPPS003",
	"INTERFACE_STEAMAPPS004",
	"INTERFACE_STEAMAPPS005",
	"INTERFACE_STEAMAPPS006",
	"INTERFACE_STEAMAPPS007",

	"INTERFACE_STEAMBILLING001",
	"INTERFACE_STEAMBILLING002",
	"INTERFACE_STEAMBILLING003",

	"INTERFACE_STEAMCLIENT001",
	"INTERFACE_STEAMCLIENT002",
	"INTERFACE_STEAMCLIENT003",
	"INTERFACE_STEAMCLIENT004",
	"INTERFACE_STEAMCLIENT005",
	"INTERFACE_STEAMCLIENT006",
	"INTERFACE_STEAMCLIENT007",
	"INTERFACE_STEAMCLIENT008",
	"INTERFACE_STEAMCLIENT009",
	"INTERFACE_STEAMCLIENT010",
	"INTERFACE_STEAMCLIENT011",
	"INTERFACE_STEAMCLIENT012",
	// [...]
	"INTERFACE_STEAMCLIENT016",
	"INTERFACE_STEAMCLIENT017",

	"INTERFACE_STEAMCONTENTSERVER001",
	"INTERFACE_STEAMCONTENTSERVER002",

	"INTERFACE_STEAMFRIENDS001",
	"INTERFACE_STEAMFRIENDS002",
	"INTERFACE_STEAMFRIENDS003",
	"INTERFACE_STEAMFRIENDS004",
	"INTERFACE_STEAMFRIENDS005",
	"INTERFACE_STEAMFRIENDS006",
	"INTERFACE_STEAMFRIENDS007",
	"INTERFACE_STEAMFRIENDS008",
	"INTERFACE_STEAMFRIENDS009",
	"INTERFACE_STEAMFRIENDS010",
	"INTERFACE_STEAMFRIENDS011",
	"INTERFACE_STEAMFRIENDS012",
	"INTERFACE_STEAMFRIENDS013",
	"INTERFACE_STEAMFRIENDS014",
	"INTERFACE_STEAMFRIENDS015",

	"INTERFACE_STEAMGAMECOORDINATOR001",

	"INTERFACE_STEAMGAMESERVER001",
	"INTERFACE_STEAMGAMESERVER002",
	"INTERFACE_STEAMGAMESERVER003",
	"INTERFACE_STEAMGAMESERVER004",
	"INTERFACE_STEAMGAMESERVER005",
	"INTERFACE_STEAMGAMESERVER006",
	"INTERFACE_STEAMGAMESERVER007",
	"INTERFACE_STEAMGAMESERVER008",
	"INTERFACE_STEAMGAMESERVER009",
	"INTERFACE_STEAMGAMESERVER010",
	"INTERFACE_STEAMGAMESERVER011",
	"INTERFACE_STEAMGAMESERVER012",

	"INTERFACE_STEAMGAMESERVERSTATS001",

	"INTERFACE_STEAMGAMESTATS001",

	"INTERFACE_STEAMHTTP001",
	"INTERFACE_STEAMHTTP002",

	"INTERFACE_STEAMMASTERUPDATER001",

	"INTERFACE_STEAMMATCHMAKING001",
	"INTERFACE_STEAMMATCHMAKING002",
	"INTERFACE_STEAMMATCHMAKING003",
	"INTERFACE_STEAMMATCHMAKING004",
	"INTERFACE_STEAMMATCHMAKING005",
	"INTERFACE_STEAMMATCHMAKING006",
	"INTERFACE_STEAMMATCHMAKING007",
	"INTERFACE_STEAMMATCHMAKING008",
	"INTERFACE_STEAMMATCHMAKING009",

	"INTERFACE_STEAMMATCHMAKINGSERVERS001",
	"INTERFACE_STEAMMATCHMAKINGSERVERS002",

	"INTERFACE_STEAMMUSIC001",

	"INTERFACE_STEAMNETWORKING001",
	"INTERFACE_STEAMNETWORKING002",
	"INTERFACE_STEAMNETWORKING003",
	"INTERFACE_STEAMNETWORKING004",
	"INTERFACE_STEAMNETWORKING005",

	"INTERFACE_STEAMOAUTH001",

	"INTERFACE_STEAMREMOTESTORAGE001",
	"INTERFACE_STEAMREMOTESTORAGE002",
	"INTERFACE_STEAMREMOTESTORAGE003",
	"INTERFACE_STEAMREMOTESTORAGE004",
	"INTERFACE_STEAMREMOTESTORAGE005",
	"INTERFACE_STEAMREMOTESTORAGE006",
	"INTERFACE_STEAMREMOTESTORAGE007",
	"INTERFACE_STEAMREMOTESTORAGE008",
	"INTERFACE_STEAMREMOTESTORAGE009",
	"INTERFACE_STEAMREMOTESTORAGE010",
	"INTERFACE_STEAMREMOTESTORAGE011",
	"INTERFACE_STEAMREMOTESTORAGE012",

	"INTERFACE_STEAMSCREENSHOTS001",
	"INTERFACE_STEAMSCREENSHOTS002",

	"INTERFACE_STEAMSTREAMLAUNCHER001",

	"INTERFACE_STEAMUGC001",
	"INTERFACE_STEAMUGC002",

	"INTERFACE_STEAMUNIFIEDMESSAGES001",

	"INTERFACE_STEAMUSER001",
	"INTERFACE_STEAMUSER002",
	"INTERFACE_STEAMUSER003",
	"INTERFACE_STEAMUSER004",
	"INTERFACE_STEAMUSER005",
	"INTERFACE_STEAMUSER006",
	"INTERFACE_STEAMUSER007",
	"INTERFACE_STEAMUSER008",
	"INTERFACE_STEAMUSER009",
	"INTERFACE_STEAMUSER010",
	"INTERFACE_STEAMUSER011",
	"INTERFACE_STEAMUSER012",
	"INTERFACE_STEAMUSER013",
	"INTERFACE_STEAMUSER014",
	"INTERFACE_STEAMUSER015",
	"INTERFACE_STEAMUSER016",
	"INTERFACE_STEAMUSER017",

	"INTERFACE_STEAMUSERSTATS001",
	"INTERFACE_STEAMUSERSTATS002",
	"INTERFACE_STEAMUSERSTATS003",
	"INTERFACE_STEAMUSERSTATS004",
	"INTERFACE_STEAMUSERSTATS005",
	"INTERFACE_STEAMUSERSTATS006",
	"INTERFACE_STEAMUSERSTATS007",
	"INTERFACE_STEAMUSERSTATS008",
	"INTERFACE_STEAMUSERSTATS009",
	"INTERFACE_STEAMUSERSTATS010",
	"INTERFACE_STEAMUSERSTATS011",

	"INTERFACE_STEAMUTILS001",
	"INTERFACE_STEAMUTILS002",
	"INTERFACE_STEAMUTILS003",
	"INTERFACE_STEAMUTILS004",
	"INTERFACE_STEAMUTILS005",
	"INTERFACE_STEAMUTILS006",
	"INTERFACE_STEAMUTILS007",
	0,
};

std::unordered_map<SteamInterface_t, void *> InterfaceManager::Instances;

void *InterfaceManager::GetInterface(SteamInterface_t interfaceID)
{
	if (Instances.find(interfaceID) == Instances.end())
	{
		Instances[interfaceID] = CreateInterface(interfaceID);
	}

	return Instances[interfaceID];
}
void *InterfaceManager::CreateInterface(SteamInterface_t interfaceID)
{
	HHSDBG();

	Log::Debug("SteamAPI", "'%s' (%d)!", InterfaceManager::SteamInterfaces[interfaceID], interfaceID);
	switch (interfaceID)
	{
		ADD_INTERFACE(INTERFACE_STEAMAPPS001, SteamApps001)
		ADD_INTERFACE(INTERFACE_STEAMAPPS002, SteamApps002)
		ADD_INTERFACE(INTERFACE_STEAMAPPS003, SteamApps003)
		ADD_INTERFACE(INTERFACE_STEAMAPPS004, SteamApps004)
		ADD_INTERFACE(INTERFACE_STEAMAPPS005, SteamApps005)
		ADD_INTERFACE(INTERFACE_STEAMAPPS006, SteamApps006)
//		ADD_INTERFACE(INTERFACE_STEAMAPPS007, SteamApps007)

// 		ADD_INTERFACE(INTERFACE_STEAMBILLING001, void)
// 		ADD_INTERFACE(INTERFACE_STEAMBILLING002, void)
// 		ADD_INTERFACE(INTERFACE_STEAMBILLING003, void)


		ADD_INTERFACE(INTERFACE_STEAMCLIENT001, void*)
		ADD_INTERFACE(INTERFACE_STEAMCLIENT002, void*)
		ADD_INTERFACE(INTERFACE_STEAMCLIENT003, void*)
		ADD_INTERFACE(INTERFACE_STEAMCLIENT004, void*)
		ADD_INTERFACE(INTERFACE_STEAMCLIENT005, void*)
		ADD_INTERFACE(INTERFACE_STEAMCLIENT006, SteamClient006)
		ADD_INTERFACE(INTERFACE_STEAMCLIENT007, SteamClient007)
		ADD_INTERFACE(INTERFACE_STEAMCLIENT008, SteamClient008)
		ADD_INTERFACE(INTERFACE_STEAMCLIENT009, SteamClient009)
		ADD_INTERFACE(INTERFACE_STEAMCLIENT010, SteamClient010)
		ADD_INTERFACE(INTERFACE_STEAMCLIENT011, SteamClient011)
		ADD_INTERFACE(INTERFACE_STEAMCLIENT012, SteamClient012)
//		// [...]
// 		ADD_INTERFACE(INTERFACE_STEAMCLIENT016, void)
// 		ADD_INTERFACE(INTERFACE_STEAMCLIENT017, void)

		ADD_INTERFACE(INTERFACE_STEAMCONTENTSERVER001, SteamContentServer001)
		ADD_INTERFACE(INTERFACE_STEAMCONTENTSERVER002, SteamContentServer002)

		ADD_INTERFACE(INTERFACE_STEAMFRIENDS001, SteamFriends001)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS002, SteamFriends002)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS003, SteamFriends003)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS004, SteamFriends004)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS005, SteamFriends005)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS006, SteamFriends006)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS007, SteamFriends007)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS008, SteamFriends008)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS009, SteamFriends009)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS010, SteamFriends010)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS011, SteamFriends011)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS012, SteamFriends012)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS013, SteamFriends013)
		ADD_INTERFACE(INTERFACE_STEAMFRIENDS014, SteamFriends014)
//		ADD_INTERFACE(INTERFACE_STEAMFRIENDS015, SteamFriends015)

		ADD_INTERFACE(INTERFACE_STEAMGAMECOORDINATOR001, SteamGameCoordinator001)

		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER001, void*)
		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER002, SteamGameServer002)
		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER003, SteamGameServer003)
		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER004, SteamGameServer004)
		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER005, SteamGameServer005)
		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER006, SteamGameServer006)
		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER007, SteamGameServer007)
		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER008, SteamGameServer008)
		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER009, SteamGameServer009)
		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER010, SteamGameServer010)
		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER011, SteamGameServer011)
// 		ADD_INTERFACE(INTERFACE_STEAMGAMESERVER012, void)

		ADD_INTERFACE(INTERFACE_STEAMGAMESERVERSTATS001, SteamGameServerStats001)

		ADD_INTERFACE(INTERFACE_STEAMGAMESTATS001, SteamGameStats001)

 		ADD_INTERFACE(INTERFACE_STEAMHTTP001, SteamHTTP001)
		ADD_INTERFACE(INTERFACE_STEAMHTTP002, SteamHTTP002)

//		ADD_INTERFACE(INTERFACE_STEAMMASTERUPDATER001, void)

 		ADD_INTERFACE(INTERFACE_STEAMMATCHMAKING001, SteamMatchmaking001)
 		ADD_INTERFACE(INTERFACE_STEAMMATCHMAKING002, SteamMatchmaking002)
 		ADD_INTERFACE(INTERFACE_STEAMMATCHMAKING003, SteamMatchmaking003)
 		ADD_INTERFACE(INTERFACE_STEAMMATCHMAKING004, SteamMatchmaking004)
 		ADD_INTERFACE(INTERFACE_STEAMMATCHMAKING005, SteamMatchmaking005)
 		ADD_INTERFACE(INTERFACE_STEAMMATCHMAKING006, SteamMatchmaking006)
 		ADD_INTERFACE(INTERFACE_STEAMMATCHMAKING007, SteamMatchmaking007)
 		ADD_INTERFACE(INTERFACE_STEAMMATCHMAKING008, SteamMatchmaking008)
 		ADD_INTERFACE(INTERFACE_STEAMMATCHMAKING009, SteamMatchmaking009)

		ADD_INTERFACE(INTERFACE_STEAMMATCHMAKINGSERVERS001, SteamMatchmakingServers001)
		ADD_INTERFACE(INTERFACE_STEAMMATCHMAKINGSERVERS002, SteamMatchmakingServers002)

//		ADD_INTERFACE(INTERFACE_STEAMMUSIC001, void)

		ADD_INTERFACE(INTERFACE_STEAMNETWORKING001, SteamNetworking001)
		ADD_INTERFACE(INTERFACE_STEAMNETWORKING002, SteamNetworking002)
		ADD_INTERFACE(INTERFACE_STEAMNETWORKING003, SteamNetworking003)
		ADD_INTERFACE(INTERFACE_STEAMNETWORKING004, SteamNetworking004)
		ADD_INTERFACE(INTERFACE_STEAMNETWORKING005, SteamNetworking005)

//		ADD_INTERFACE(INTERFACE_STEAMOAUTH001, void)

 		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE001, SteamRemoteStorage001)
		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE002, SteamRemoteStorage002)
		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE003, SteamRemoteStorage003)
		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE004, SteamRemoteStorage004)
		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE005, SteamRemoteStorage005)
		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE006, SteamRemoteStorage006)
		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE007, SteamRemoteStorage007)
		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE008, SteamRemoteStorage008)
		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE009, SteamRemoteStorage009)
		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE010, SteamRemoteStorage010)
		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE011, SteamRemoteStorage011)
		ADD_INTERFACE(INTERFACE_STEAMREMOTESTORAGE012, SteamRemoteStorage012)

//		ADD_INTERFACE(INTERFACE_STEAMSCREENSHOTS001, void)
//		ADD_INTERFACE(INTERFACE_STEAMSCREENSHOTS002, void)

//		ADD_INTERFACE(INTERFACE_STEAMSTREAMLAUNCHER001, void)

// 		ADD_INTERFACE(INTERFACE_STEAMUGC001, void)
// 		ADD_INTERFACE(INTERFACE_STEAMUGC002, void)

//		ADD_INTERFACE(INTERFACE_STEAMUNIFIEDMESSAGES001, void)

		ADD_INTERFACE(INTERFACE_STEAMUSER001, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER002, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER003, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER004, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER005, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER006, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER007, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER008, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER009, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER010, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER011, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER012, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER013, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER014, void*)
 		ADD_INTERFACE(INTERFACE_STEAMUSER015, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSER016, SteamUser016)
// 		ADD_INTERFACE(INTERFACE_STEAMUSER017, void)

ADD_INTERFACE(INTERFACE_STEAMUSERSTATS001, void*)
ADD_INTERFACE(INTERFACE_STEAMUSERSTATS002, void*)
ADD_INTERFACE(INTERFACE_STEAMUSERSTATS003, void*)
ADD_INTERFACE(INTERFACE_STEAMUSERSTATS004, void*)
ADD_INTERFACE(INTERFACE_STEAMUSERSTATS005, void*)
ADD_INTERFACE(INTERFACE_STEAMUSERSTATS006, void*)
ADD_INTERFACE(INTERFACE_STEAMUSERSTATS007, void*)
ADD_INTERFACE(INTERFACE_STEAMUSERSTATS008, void*)
ADD_INTERFACE(INTERFACE_STEAMUSERSTATS009, void*)
ADD_INTERFACE(INTERFACE_STEAMUSERSTATS010, void*)
		ADD_INTERFACE(INTERFACE_STEAMUSERSTATS011, SteamUserStats011)

 		ADD_INTERFACE(INTERFACE_STEAMUTILS001, void*)
 		ADD_INTERFACE(INTERFACE_STEAMUTILS002, void*)
 		ADD_INTERFACE(INTERFACE_STEAMUTILS003, void*)
 		ADD_INTERFACE(INTERFACE_STEAMUTILS004, void*)
 		ADD_INTERFACE(INTERFACE_STEAMUTILS005, SteamUtils005)
 		ADD_INTERFACE(INTERFACE_STEAMUTILS006, void*)
 		ADD_INTERFACE(INTERFACE_STEAMUTILS007, void*)

	default:
		break;
	}

	/*auto message = hString::va("Missing handler for interface '%s' (%d)!", InterfaceManager::SteamInterfaces[interfaceID], interfaceID);

	hConsole::EnqueueMessage("ERR", (char *)hString::va("InterfaceManager: %s", message), "");
	MessageBoxA(0, message, "Error", MB_ICONERROR);*/
	return NULL;
}